debug:
    logging:
        configuration: debug
        initialization: debug
        collision_space: debug
        kinematics: debug
        hashmanager: debug
        search: debug
        motionprimitives: debug
